name: Package Preview

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Build preview zip
        uses: BigWigsMods/packager@v2
        with:
          args: -d -g retail -r preview-package

      - name: Upload preview zip
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: preview-package/VehicleBars*.zip
          if-no-files-found: error
          retention-days: 14
