name: Package Preview

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build preview zip
        uses: BigWigsMods/packager@v2
        with:
          args: -d -g retail

      - name: Upload preview zip
        uses: actions/upload-artifact@v4
        with:
          name: VehicleBars-preview
          path: .release/VehicleBars*.zip
          if-no-files-found: error
          retention-days: 14
